version: "3"

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PRISMA_URL=postgresql://postgres:postgres@db:5432/postgres&connection_limit=1
      - POSTGRES_URL_NON_POOLING=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
